version: '3.9'
services:
  asp.chat.web:
    container_name: asp.chat.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - "${PWD}/.env:/App/.env"
    depends_on:
      - asp.chat.db
    networks:
      - asp.chat.network
    restart: always

  asp.chat.db:
    container_name: asp.chat.db
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=passwordHard!_+1s2t394
      - MSSQL_PID=Express
    networks:
      - asp.chat.network
    restart: always

networks:
  asp.chat.network:
    name: asp.chat.network
    driver: bridge