version: '3.9'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - dotnetn
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=passwordHard!_+1s2t394
      - MSSQL_PID=Express
    networks:
      - dotnetn

networks:
  dotnetn:
    name: dotnetn
    driver: bridge