version: '3.9'
services:
  web:
    container_name: chatweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - "${PWD}/.env:/App/.env"
    depends_on:
      - db
    # networks:
    #   - dotwork
  db:
    container_name: chatdb
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=passwordHard!_+1s2t394
      - MSSQL_PID=Express
    # networks:
    #   - dotwork

# networks:
#   dotwork:
#     external: true
#     name: dotwork    